### PR TITLE
have the option to walk to the center of an world position

### PR DESCRIPTION
**Pull request by ebf34e12952930cf**
this may or may not be the most efficient way

### CODE REVIEW

**Comment by toddw123** [comment]
Hmm what would be the importance of this? As it stands now, the WorldPosData x/y are already floats, why not just set the target x/y to the center before calling the moveTo?

**Comment by ebf34e12952930cf** [comment]
hm, yea true. i guess it removes the need to not have that code in other places?

**Comment by toddw123** [comment]
I guess that is fine, but id rather have it be false by default, that way it doesnt change the target data unless you specifically tell it to change the target data.

**Comment by ebf34e12952930cf** [comment]
yea i realized that after i commited it, ill change it

**Pull request merged**
