### PR TITLE
Added libraries for easier setup

### PR DESCRIPTION
**Pull request by VoOoLoX**

### CODE REVIEW

**Comment by EinarasGar** [comment]
Lol way to get +87k lines of code in someones elses project :DDD

**Comment by Zeroeh** [comment]
LOL!

**Comment by Zeroeh** [comment]
The easier way to fix this would be to just add the .vcxproj files to the gitignore so not everyone is uploading their custom directories.

**Comment by VoOoLoX** [comment]
I used VS macros for directories so it should work on every PC

**Comment by toddw123** [comment]
Yes im not adding these to my project, sorry. If someone needs help setting up the libraries they can ask, but theres no reason to include them here as well. 

As Zeroeh said, adding .vcxproj files to gitignore might be be best.

**Pull request closed without merging**
