### PR TITLE
Just to be safe

### PR DESCRIPTION
**Pull request by VoOoLoX**
Fix for the `memcpy` and `memset` errors

### CODE REVIEW

**Comment by toddw123** [comment]
PacketIO.cpp has "Packet.h" included, which already has `#include <string>`. So theres no need to add it to the PacketIO.h file (you want to limit as many headers as you can in .h files and instead try to put as many as possible into the .cpp file).

I also dont get any warning or anything in regards to the micropather file needing it either.

**Comment by VoOoLoX** [comment]
I just updated my system and tried to compile it. And got errors about memcpy and memset .
Yeah i noticed `Packet.h` has a string included but check this out http://i.imgur.com/lDEYZ4G.png

**Comment by toddw123** [comment]
Mmkay. Redo this though and put the <cstring> header in the .cpp files instead. Then ill pull this into the master branch.

**Comment by VoOoLoX** [comment]
`memset` is used in `micropather` header file so couldn't move that one

**Comment by toddw123** [comment]
> memset is used in micropather header file so couldn't move that one

That makes sense. With it moved to the .cpp file for PacketIO, were you able to compile without issue?

**Comment by VoOoLoX** [comment]
Yeah since `memcpy` is used in source file only, not in the header file.

**Pull request merged**
